# Generated by Django 6.0.6 on 2026-06-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('completed', 'Completado')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artist_jobs', to='auth.User')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_requests', to='auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_type', models.CharField(blank=True, choices=[('before', 'Antes'), ('after', 'Después'), ('progress', 'Progreso')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='chat.jobrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='auth.User')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('artist', 'Artista')], default='client', max_length=15)),
                ('last_round_robin', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'assigned', 'completed'])), name='check_job_request_status'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['job_request', 'created_at'], name='idx_msg_job_request_created'),
        ),
    ]