# Generated by Django 6.0.6 on 2026-06-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_type',
            field=models.CharField(blank=True, choices=[('before', 'Antes'), ('after', 'Después'), ('progress', 'Progreso')], max_length=10, null=True),
        ),
    ]
