# Generated by Django 6.0.6 on 2026-06-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_image_message_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_round_robin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
