# Generated by Django 6.0.6 on 2026-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_last_round_robin_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
